# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool:
  vmImage: ubuntu-latest


- task: Kubernetes@1
  inputs:
    connectionType: 'KubernetesServiceConnection'
    kubernetesServiceEndpoint: 'gcp-dinar-development-development-1732535429861'  
    namespace: 'default'
    command: 'apply'
    arguments: '-f $(Build.SourcesDirectory)/nginx-deployment.yaml'
    containerName: 'nginx'
    secretName: 'nginx-secret'

