name: Deploy NGINX to GKE

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    # 1. Checkout the repository code
    - name: Checkout
      uses: actions/checkout@v4
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/930524074535/locations/global/workloadIdentityPools/git-actions-pool/providers/github'
        service_account: 'github@dinar-0092.iam.gserviceaccount.com'

    # 2. Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
        location: ${{ secrets.GKE_CLUSTER_ZONE }}


    # 4. Configure Docker login
    - name: Docker login
      run: |-
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://${{ secrets.GCP_GAR_LOCATION }}-docker.pkg.dev

    # 6. Build and push the NGINX Docker image to Google Container Registry
    - name: Build and push NGINX Docker image to GCR
      run: |

        docker build -t ${{ secrets.GCP_GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/test/nginx:1 .        
        docker push ${{ secrets.GCP_GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/test/nginx:1 

#    # 6A. debug
#    - name: Debugging - List deploy directory
#      run: |
#        echo "Current directory: $(pwd)"
#        echo "Listing files in deploy directory:"
#        ls -ltrh ./k8s || echo "Deploy directory not found"

    # 7. Deploy the Docker image to the GKE cluster
    - name: Deploy to GKE 
      run: |-
        kubectl apply -f ./k8s/nginx-deployment.yaml
        kubectl get pods -n default -o wide

